packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.31.0
  '@ianvs/prettier-plugin-sort-imports': ^4.5.1
  '@types/lodash.defaultsdeep': ^4.6.9
  '@types/lodash.set': ^4.3.9
  '@types/node': 24.0.13
  '@vitest/browser': ^3.2.4
  date-fns: 4.1.0
  eslint: 9.31.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.4
  eslint-plugin-unused-imports: ^4.1.4
  globals: ^16.3.0
  lodash.defaultsdeep: ^4.6.1
  lodash.set: ^4.3.2
  playwright: ^1.54.1
  prettier: 3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  tsx: ^4.20.3
  type-fest: 4.41.0
  typescript: 5.8.3
  typescript-eslint: ^8.36.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  yaml: ^2.8.0
  zod: ^4.0.5

catalogMode: strict
