packages:
  - apps/*
  - packages/*

catalog:
  '@docusaurus/core': 3.8.1
  '@docusaurus/module-type-aliases': ^3.8.1
  '@docusaurus/preset-classic': 3.8.1
  '@docusaurus/tsconfig': ^3.8.1
  '@docusaurus/types': ^3.8.1
  '@eslint/js': ^9.31.0
  '@fontsource-variable/rethink-sans': 5.2.6
  '@fontsource-variable/saira': 5.2.8
  '@ianvs/prettier-plugin-sort-imports': ^4.5.1
  '@mdx-js/react': ^3.1.0
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-slider': ^1.3.5
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': ^1.2.5
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/react-form': 1.14.1
  '@tanstack/react-router': ^1.128.3
  '@tanstack/react-router-devtools': ^1.128.3
  '@tanstack/router-plugin': ^1.128.3
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.3.0
  '@types/lodash.defaultsdeep': ^4.6.9
  '@types/lodash.set': ^4.3.9
  '@types/node': 24.0.13
  '@types/react': 19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.7.0
  '@vitest/browser': ^3.2.4
  class-variance-authority: ^0.7.1
  clsx: 2.1.1
  concurrently: ^9.2.0
  date-fns: 4.1.0
  docusaurus-plugin-typedoc: ^1.4.0
  eslint: 9.31.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.4
  eslint-plugin-unused-imports: ^4.1.4
  globals: ^16.3.0
  jsdom: ^26.1.0
  lodash.defaultsdeep: ^4.6.1
  lodash.set: ^4.3.2
  lucide-react: 0.525.0
  plausible-tracker: ^0.3.9
  playwright: ^1.54.1
  prettier: 3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  prism-react-renderer: ^2.4.1
  react: 19.1.0
  react-dom: 19.1.0
  tailwind-merge: 3.3.1
  tailwindcss: ^4.1.11
  tsc-alias: ^1.8.16
  tsx: ^4.20.3
  tw-animate-css: ^1.3.5
  type-fest: 4.41.0
  typedoc: ^0.28.7
  typedoc-plugin-markdown: ^4.7.1
  typescript: 5.8.3
  typescript-eslint: ^8.36.0
  vite: ^7.0.5
  vite-plugin-checker: ^0.10.1
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  web-vitals: ^5.0.3
  yaml: ^2.8.0
  zod: 4.0.5

catalogMode: strict
