import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  librairies: [
    {
      type: "autogenerated",
      dirName: "librairies",
    },
  ],
  simulateurs: [
    "simulateurs/index",
    {
      type: "category",
      label: "Simulateurs",
      collapsed: false,
      items: ["simulateurs/concubinage-vs-pacs"],
    },
  ],
};

export default sidebars;
