import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  librairies: [
    {
      type: "autogenerated",
      dirName: "librairies",
    },
  ],
  simulateurs: [
    {
      type: "autogenerated",
      dirName: "simulateurs",
    },
  ],
};

export default sidebars;
