/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OAkimeoSSlugRouteImport } from './routes/o/akimeo/s/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OAkimeoSSlugRoute = OAkimeoSSlugRouteImport.update({
  id: '/o/akimeo/s/$slug',
  path: '/o/akimeo/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o/akimeo/s/$slug': typeof OAkimeoSSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o/akimeo/s/$slug': typeof OAkimeoSSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o/akimeo/s/$slug': typeof OAkimeoSSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/o/akimeo/s/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/o/akimeo/s/$slug'
  id: '__root__' | '/' | '/o/akimeo/s/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OAkimeoSSlugRoute: typeof OAkimeoSSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/akimeo/s/$slug': {
      id: '/o/akimeo/s/$slug'
      path: '/o/akimeo/s/$slug'
      fullPath: '/o/akimeo/s/$slug'
      preLoaderRoute: typeof OAkimeoSSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OAkimeoSSlugRoute: OAkimeoSSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
